### PR TITLE
Bump jest to 28

### PR DESCRIPTION
**Pull request by ronjouch**
https://jestjs.io/blog/2022/04/25/jest-28
https://jestjs.io/docs/upgrading-to-jest28
https://github.com/facebook/jest/blob/main/CHANGELOG.md#2800

Causes playwright tests to fail in CI & on my machine,
but I can't troubleshoot because they fail differently
(always have been) on my machine :-/ .

### CODE REVIEW

**Comment by ronjouch** [comment]
@TheCleric can you take a look?

In CI, with this PR, Playwright tests fail (example [test run](https://github.com/nativefier/nativefier/runs/7484198075?check_suite_focus=true)) with a weird `No tests found, exiting with code 1` :thinking: .

And I'd like to troubleshoot, but on my machine, the Playwright test runs, but fails (before or after the Jest upgrade):

<details>
  <summary>Logs for how Playwright tests fail on my machine</summary>

```
19:38:03 ~/f/nativefier (master|✔) npm ci && npm run build && npm run test:playwright 

> nativefier@47.2.1 prepare
> cd app && npm ci && cd .. && npm run build


added 123 packages, and audited 124 packages in 5s

15 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> nativefier@47.2.1 build
> npm run clean && tsc --build shared src app && npm run build-app && npm run build-app-static


> nativefier@47.2.1 clean
> rimraf coverage/ lib/ app/lib/ app/dist/ shared/lib


> nativefier@47.2.1 build-app
> cd app && webpack

assets by path ../dist/app/src/ 8.11 KiB
  assets by path ../dist/app/src/helpers/*.ts 4.87 KiB
    asset ../dist/app/src/helpers/windowHelpers.d.ts 1.97 KiB [emitted]
    asset ../dist/app/src/helpers/helpers.d.ts 1.13 KiB [emitted]
    + 7 assets
  assets by path ../dist/app/src/components/*.ts 1.53 KiB
    asset ../dist/app/src/components/mainWindow.d.ts 498 bytes [emitted]
    asset ../dist/app/src/components/menu.d.ts 419 bytes [emitted]
    + 4 assets
  assets by path ../dist/app/src/*.ts 79 bytes
    asset ../dist/app/src/preload.d.ts 41 bytes [emitted]
    asset ../dist/app/src/main.d.ts 38 bytes [emitted]
  asset ../dist/app/src/mocks/electron.d.ts 1.64 KiB [emitted]
asset main.js 491 KiB [emitted] (name: main) 1 related asset
asset ../dist/shared/src/options/model.d.ts 5.81 KiB [emitted]
runtime modules 123 bytes 1 module
modules by path ./node_modules/ 397 KiB 56 modules
modules by path ./src/ 84.1 KiB
  modules by path ./src/helpers/*.ts 33.6 KiB 6 modules
  modules by path ./src/components/*.ts 35 KiB
    ./src/components/loginWindow.ts 2.11 KiB [built] [code generated]
    + 4 modules
  ./src/main.ts 15.6 KiB [built] [code generated]
+ 12 modules
webpack 5.73.0 compiled successfully in 4225 ms

> nativefier@47.2.1 build-app-static
> ncp app/src/static/ app/lib/static/ && ncp app/dist/preload.js app/lib/preload.js && ncp app/dist/preload.js.map app/lib/preload.js.map


added 729 packages, and audited 730 packages in 26s

89 packages are looking for funding
  run `npm fund` for details

4 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> nativefier@47.2.1 build
> npm run clean && tsc --build shared src app && npm run build-app && npm run build-app-static


> nativefier@47.2.1 clean
> rimraf coverage/ lib/ app/lib/ app/dist/ shared/lib


> nativefier@47.2.1 build-app
> cd app && webpack

assets by path ../dist/app/src/ 8.11 KiB
  assets by path ../dist/app/src/helpers/*.ts 4.87 KiB
    asset ../dist/app/src/helpers/windowHelpers.d.ts 1.97 KiB [emitted]
    asset ../dist/app/src/helpers/helpers.d.ts 1.13 KiB [emitted]
    + 7 assets
  assets by path ../dist/app/src/components/*.ts 1.53 KiB
    asset ../dist/app/src/components/mainWindow.d.ts 498 bytes [emitted]
    asset ../dist/app/src/components/menu.d.ts 419 bytes [emitted]
    + 4 assets
  assets by path ../dist/app/src/*.ts 79 bytes
    asset ../dist/app/src/preload.d.ts 41 bytes [emitted]
    asset ../dist/app/src/main.d.ts 38 bytes [emitted]
  asset ../dist/app/src/mocks/electron.d.ts 1.64 KiB [emitted]
asset main.js 491 KiB [emitted] (name: main) 1 related asset
asset ../dist/shared/src/options/model.d.ts 5.81 KiB [emitted]
runtime modules 123 bytes 1 module
modules by path ./node_modules/ 397 KiB 56 modules
modules by path ./src/ 84.1 KiB
  modules by path ./src/helpers/*.ts 33.6 KiB 6 modules
  modules by path ./src/components/*.ts 35 KiB
    ./src/components/loginWindow.ts 2.11 KiB [built] [code generated]
    + 4 modules
  ./src/main.ts 15.6 KiB [built] [code generated]
+ 12 modules
webpack 5.73.0 compiled successfully in 4186 ms

> nativefier@47.2.1 build-app-static
> ncp app/src/static/ app/lib/static/ && ncp app/dist/preload.js app/lib/preload.js && ncp app/dist/preload.js.map app/lib/preload.js.map


> nativefier@47.2.1 test:playwright
> jest --detectOpenHandles --testRegex '.*playwright-test.js'

 FAIL  lib/playwright-test.js (18.829 s)
  Application launch
    ✕ shows an initial window (4283 ms)
    ✕ can inject some CSS (1939 ms)
    ✕ can inject some JS (1972 ms)
    ✕ can open internal links (2075 ms)
    ✕ tries to open external links (1944 ms)
    ✕ no errors thrown in console (1918 ms)
    ✕ basic auth (1975 ms)
    ✕ basic auth without pre-providing (1956 ms)
    ○ skipped keyboard shortcuts: zoom
    ○ skipped keyboard shortcuts: back and forward

  ● Application launch › shows an initial window

    electron.launch: Process failed to launch!

      66 |         .catch(() => log.log('window.console', consoleMessage));
      67 |     };
    > 68 |     app = await _electron.launch({
         |           ^
      69 |       args: [appMainJSPath],
      70 |       env: {
      71 |         LOG_FILE_DIR: logFileDir,

      at spawnApp (src/playwright-test.ts:68:11)
      at Object.<anonymous> (src/playwright-test.ts:129:25)

  ● Application launch › can inject some CSS

    electron.launch: Process failed to launch!

      66 |         .catch(() => log.log('window.console', consoleMessage));
      67 |     };
    > 68 |     app = await _electron.launch({
         |           ^
      69 |       args: [appMainJSPath],
      70 |       env: {
      71 |         LOG_FILE_DIR: logFileDir,

      at spawnApp (src/playwright-test.ts:68:11)
      at Object.<anonymous> (src/playwright-test.ts:141:25)

  ● Application launch › can inject some JS

    electron.launch: Process failed to launch!

      66 |         .catch(() => log.log('window.console', consoleMessage));
      67 |     };
    > 68 |     app = await _electron.launch({
         |           ^
      69 |       args: [appMainJSPath],
      70 |       env: {
      71 |         LOG_FILE_DIR: logFileDir,

      at spawnApp (src/playwright-test.ts:68:11)
      at Object.<anonymous> (src/playwright-test.ts:162:25)

  ● Application launch › can open internal links

    electron.launch: Process failed to launch!

      66 |         .catch(() => log.log('window.console', consoleMessage));
      67 |     };
    > 68 |     app = await _electron.launch({
         |           ^
      69 |       args: [appMainJSPath],
      70 |       env: {
      71 |         LOG_FILE_DIR: logFileDir,

      at spawnApp (src/playwright-test.ts:68:11)
      at Object.<anonymous> (src/playwright-test.ts:178:25)

  ● Application launch › tries to open external links

    electron.launch: Process failed to launch!

      66 |         .catch(() => log.log('window.console', consoleMessage));
      67 |     };
    > 68 |     app = await _electron.launch({
         |           ^
      69 |       args: [appMainJSPath],
      70 |       env: {
      71 |         LOG_FILE_DIR: logFileDir,

      at spawnApp (src/playwright-test.ts:68:11)
      at Object.<anonymous> (src/playwright-test.ts:186:25)

  ● Application launch › no errors thrown in console

    electron.launch: Process failed to launch!

      66 |         .catch(() => log.log('window.console', consoleMessage));
      67 |     };
    > 68 |     app = await _electron.launch({
         |           ^
      69 |       args: [appMainJSPath],
      70 |       env: {
      71 |         LOG_FILE_DIR: logFileDir,

      at spawnApp (src/playwright-test.ts:68:11)
      at Object.<anonymous> (src/playwright-test.ts:285:5)

  ● Application launch › basic auth

    electron.launch: Process failed to launch!

      66 |         .catch(() => log.log('window.console', consoleMessage));
      67 |     };
    > 68 |     app = await _electron.launch({
         |           ^
      69 |       args: [appMainJSPath],
      70 |       env: {
      71 |         LOG_FILE_DIR: logFileDir,

      at spawnApp (src/playwright-test.ts:68:11)
      at Object.<anonymous> (src/playwright-test.ts:305:25)

  ● Application launch › basic auth without pre-providing

    electron.launch: Process failed to launch!

      66 |         .catch(() => log.log('window.console', consoleMessage));
      67 |     };
    > 68 |     app = await _electron.launch({
         |           ^
      69 |       args: [appMainJSPath],
      70 |       env: {
      71 |         LOG_FILE_DIR: logFileDir,

      at spawnApp (src/playwright-test.ts:68:11)
      at Object.<anonymous> (src/playwright-test.ts:328:25)

```
</details>

@TheCleric can you take a look? Do these tests run for you locally?

**Comment by TheCleric** [comment]
@ronjouch I'll take a look shortly. Try adding `DEBUG=pw:browser*` before the test command locally to see more playwright output on why yours may be failing to launch.

**Comment by ronjouch** [comment]
> @ronjouch I'll take a look shortly. Try adding `DEBUG=pw:browser*` before the test command locally to see more playwright output on why yours may be failing to launch.

@TheCleric thanks. That helps, but even in master, playwright tests fail in a way that I have zarroo idea why they work on master: tests crash with an error `Not loading override URL passed as argument, because failed to parse: --inspect=0 TypeError: Invalid URL`. So, in `main.ts` code, at a spot where we're supposed to be working with a URL, we have an Electron option, WTF.

Not digging further, letting you take a look. Thanks.

**Comment by TheCleric** [comment]
I think it's fixed now. Agreed that it's weird that these issues JUST came up, even on master for me as well.

**Comment by TheCleric** [comment]
Jest 28 really doesn't like us 🤣. Now it can't find ANY of out tests.

```
> nativefier@4[7](https://github.com/nativefier/nativefier/runs/7485178366?check_suite_focus=true#step:5:8).2.1 test:noplaywright
> jest --testRegex '[-.]test\.js$' --testPathIgnorePatterns '.*playwright.*'
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In D:\a\nativefier\nativefier
  223 files checked.
  testMatch:  - 0 matches
  testPathIgnorePatterns: '.*playwright.*' - 223 matches
  testRegex: '[-.]test\.js$' - 0 matches
Pattern:  - 0 matches
Error: Process completed with exit code 1
```

**Comment by ronjouch** [comment]
> Jest 28 really doesn't like us rofl. Now it can't find ANY of out tests.

@TheCleric yup, was bewildered by that too in https://github.com/nativefier/nativefier/pull/1437#issuecomment-1193208289 .

I hypothesized some kind of breaking change in the inclusion/exclusion logic but couldn't find any in https://github.com/facebook/jest/blob/main/CHANGELOG.md#2800

**Comment by TheCleric** [comment]
> @TheCleric yup, was bewildered by that too in [#1437 (comment)](https://github.com/nativefier/nativefier/pull/1437#issuecomment-1193208289) .
> 
> I hypothesized some kind of breaking change in the inclusion/exclusion logic but couldn't find any in https://github.com/facebook/jest/blob/main/CHANGELOG.md#2800

@ronjouch looking more and more likely. Check the latest runs. I did a dir list to confirm the test files are there. I think we may have found a pattern though in the last run. We got ubuntu to pass before all 3 Windows runs failed for pretty much the same reason. So my guess is there is a regression in `--testRegex` in Jest 28 on Windows.

**Comment by TheCleric** [comment]
> @ronjouch looking more and more likely. Check the latest runs. I did a dir list to confirm the test files are there. I think we may have found a pattern though in the last run. We got ubuntu to pass before all 3 Windows runs failed for pretty much the same reason. So my guess is there is a regression in `--testRegex` in Jest 28 on Windows.

I forgot to note though that this doesn't apply on my Windows box at home. Tests run fine.

**Comment by ronjouch** [comment]
@TheCleric 👍, thx for looking.

**Comment by TheCleric** [comment]
> @TheCleric 👍, thx for looking.

NP. There is a separate issue here that I fixed for playwright. If you want me to get an isolated PR to fix that on master, let me know.

**Comment by ronjouch** [comment]
> NP. There is a separate issue here that I fixed for playwright. If you want me to get an isolated PR to fix that on master, let me know.

@TheCleric thx; took it and pushed it.

So, PlayWright tests no longer crash here, but now on my Linux machine, fail further with Chromium error

```
  pw:browser [pid=286188][err] [286188:0724/102939.938248:ERROR:ozone_platform_x11.cc(248)] Missing X server or $DISPLAY +77ms
  pw:browser [pid=286188][err] [286188:0724/102939.938299:ERROR:env.cc(225)] The platform failed to initialize.  Exiting. +2ms

```

Gaaaah. But I *am* running X (not Wayland), setting DISPLAY to the standard default value `DISPLAY=:0.0` doesn't help, and I'm not eager to go delve into `ozone_platform_x11.cc` to figure out what's causing this incorrect early exit.

**Comment by ronjouch** [comment]
> _We got ubuntu to pass before all 3 Windows runs failed for pretty much the same reason. So my guess is there is a regression in `--testRegex` in Jest 28 on Windows._

@TheCleric wheeeeeeeeEEEEEeeeeeeeee, your intuition was correct. I monkeyed around our setup, 1. simplifying the regexes and 2. moving them from command-line to in-config, and tests now pass, Windows, Mac, Linux, PlayWright 🙂.

I won't be digging further to find a minimal repro scenario and report it to Jest. Feel free to if you want to.

With that, merging. Thanks for your halp!

**Comment by ronjouch** [comment]
@TheCleric PW test `basic auth without pre-providing` has been flaky recently. Example runs:

- https://github.com/nativefier/nativefier/runs/7489042993?check_suite_focus=true
- https://github.com/nativefier/nativefier/runs/7489142899?check_suite_focus=true

The problem is always the same,

```
     page.evaluate: Execution context was destroyed, most likely because of a navigation
      364 |     await mainWindow.waitForLoadState('networkidle');
      365 |
    > 366 |     const documentText = await mainWindow.evaluate<string>(
          |                                           ^
      367 |       'document.documentElement.innerText',
      368 |     );
      369 |
      at Object.evaluate (src/playwright-test.ts:366:43)
```

→ Is there something else we can do?

**Comment by TheCleric** [comment]
> @TheCleric PW test `basic auth without pre-providing` has been flaky recently. Example runs:
> 
> - https://github.com/nativefier/nativefier/runs/7489042993?check_suite_focus=true
> - https://github.com/nativefier/nativefier/runs/7489142899?check_suite_focus=true
> 
> The problem is always the same,
> 
> ```
>      page.evaluate: Execution context was destroyed, most likely because of a navigation
>       364 |     await mainWindow.waitForLoadState('networkidle');
>       365 |
>     > 366 |     const documentText = await mainWindow.evaluate<string>(
>           |                                           ^
>       367 |       'document.documentElement.innerText',
>       368 |     );
>       369 |
>       at Object.evaluate (src/playwright-test.ts:366:43)
> ```
> 
> → Is there something else we can do?

I had seen this before but thought I fixed it. I'll check it out.

**Comment by TheCleric** [comment]
> @TheCleric thx; took it and pushed it.
> 
> So, PlayWright tests no longer crash here, but now on my Linux machine, fail further with a Chromium error:
> 
> ```
>   pw:browser [pid=286188][err] [286188:0724/102939.938248:ERROR:ozone_platform_x11.cc(248)] Missing X server or $DISPLAY +77ms
>   pw:browser [pid=286188][err] [286188:0724/102939.938299:ERROR:env.cc(225)] The platform failed to initialize.  Exiting. +2ms
> ```
> 
> Gaaaah. But I _am_ running X (not Wayland), setting DISPLAY to the standard default value `DISPLAY=:0.0` doesn't help, and I'm not eager to go delve into `ozone_platform_x11.cc` to figure out what's causing this incorrect early exit.

@ronjouch Maddeningly I can't reproduce on my Debian box, but instead it fails for a completely different reason:

```
  pw:browser [pid=24716][err] [24718:0100/000000.660708:ERROR:zygote_linux.cc(650)] write: Broken pipe (32) +16ms
  pw:browser [pid=24719][err] [24719:0725/114519.722060:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/parallels/Dev/nativefier/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755. +61ms
```

**Pull request merged**
