### PR TITLE
Allow setting default app destination with env. var. NATIVEFIER_APPS_DIR

### LINKED ISSUE #1336: Allow setting default app destination with environment variable
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md , no existing option fits my needs.
- [ ] I searched existing issues, open & closed. Yes, my feature request is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Problem statement**

Nativefier should allow using an env var like `NATIVEFIER_APPS_DIR` to specify the default location for apps.. This way someone could just run `nativefier example.com` from anywhere on their system and have it automatically put the app in their `~/Applications/` directory by adding `export NATIVEFIER_APPS_DIR="$HOME/Applications/"` to their `.bashrc` or similar file.  

**Suggested solution**

**Alternative solutions**

Manually setting the destination directory or `cd`-ing into it. 

**Context**

 - Nativefier: (for example: 9.1.0)
 - Node.js: (for example: 14.6.0)
 - Npm: (for example: 6.14.7)
 - OS: (for example: Windows 10 build 1809)
 - Additional context: This would be helpful for macOS users who always want their nativefier apps to go into `~/Applications/` 

I was thinking about making a dockerfile for [nativefier-catalog](https://github.com/mattruzzi/nativefier-catalog) but then realized that nativefier-catalog didn't have any way of specifying where to build the app and always would build it in the current directory and instead of adding a new command line argument or checking for the env var there it seemed better to have this be an upstream feature of nativefier itself.

### PR DESCRIPTION
**Pull request by mattruzzi**
Closes #1336

### CODE REVIEW

**Review by ronjouch — COMMENTED** [review]
👍 thx Matt. Will take, with added:

1. Documentation. Detailed in API.md, and concise in --help
2. Logging:
    1. If no explicit destination is passed: logging that we use the env. var
    2. If an explicit destination is passed: logging that we do have an env. var, but also an explicit destination, so the explicit destination overrides
2. Tests

**Comment by mattruzzi** [comment]
Should I add it to the usage section on the readme?

## Usage

To create a desktop app for medium.com, simply `nativefier 'medium.com'`

Nativefier will try to determine the app name, and well as lots of other options.
If desired, these options can be overwritten. For example, to override the name,
```sh
nativefier --name 'My Medium App' 'medium.com'
```

By default, nativefier saves apps in the current working directory. To change the output location, pass it as the second argument, or set the `NATIVEFIER_APPS_DIR` environment variable. 

To save to `~/Applications/` use 

```sh
nativefier --name 'My Medium App' 'medium.com' ~/Applications/
``` 
or
```sh
export NATIVEFIER_APPS_DIR=~/Applications/
nativefier --name 'My Medium App' 'medium.com'
```

You can also add `export NATIVEFIER_APPS_DIR=~/Applications/` to your `~/.bashrc` or similar file to set the default location. 

**Read the [API docs](API.md) or run `nativefier --help`**
to learn about command-line flags usable to configure your app.

To have high-quality icons used by default for an app/domain, please
contribute to the [icon repository](https://github.com/nativefier/nativefier-icons).

**Comment by ronjouch** [comment]
> Should I add it to the usage section on the readme?
> ## Usage
> 
> To create a desktop app for medium.com, simply `nativefier 'medium.com'`
> 
> Nativefier will try to determine the app name, and well as lots of other options. If desired, these options can be overwritten. For example, to override the name,
> 
> ```shell
> nativefier --name 'My Medium App' 'medium.com'
> ```
> 
> By default, nativefier saves apps in the current working directory. To change the output location, pass it as the second argument, or set the `NATIVEFIER_APPS_DIR` environment variable.
> 
> To save to `~/Applications/` use
> 
> ```shell
> nativefier --name 'My Medium App' 'medium.com' ~/Applications/
> ```
> 
> or
> 
> ```shell
> export NATIVEFIER_APPS_DIR=~/Applications/
> nativefier --name 'My Medium App' 'medium.com'
> ```
> 
> You can also add `export NATIVEFIER_APPS_DIR=~/Applications/` to your `~/.bashrc` or similar file to set the default location.
> 
> **Read the [API docs](API.md) or run `nativefier --help`** to learn about command-line flags usable to configure your app.
> 
> To have high-quality icons used by default for an app/domain, please contribute to the [icon repository](https://github.com/nativefier/nativefier-icons).

Only in API.md and `--help` pls. The README is intentionally concise for approchability and omit lots of details.

**Comment by ronjouch** [comment]
Neato, merging. Thanks!

**Pull request merged**
