### PR TITLE
Upgrade Electron from 13 to 16

### PR DESCRIPTION
**Pull request by TheCleric**
This PR upgrades Nativefier to Electron 14. It will stay in draft until we feel its well tested.

Major Version Checklist

- [X] Wait a few weeks to let it stabilize. Never upgrade Nativefier to a .0.0.
- [X] Thoroughly digest the new version's [breaking changes](https://www.electronjs.org/docs/latest/breaking-changes), grepping our codebase for every changed API. If called for by the breaking changes, perform the necessary API changes
- [X] Bump src/constants.ts / DEFAULT_ELECTRON_VERSION & DEFAULT_CHROME_VERSION and app / package.json / devDeps / electron
- [ ] On Windows, macOS, Linux, test for regression and crashes:
    - [x] With npm test and npm run test:manual
        - [x] MacOS
        - [ ] Windows
        - [x] Linux (@ronjouch can you handle this?)
    - [x] With extra manual testing
        - [x] MacOS
        - [ ] Windows
        - [x] Linux (@ronjouch can you handle this?)

### CODE REVIEW

**Comment by ronjouch** [comment]
@TheCleric two questions:

1. In addition to checking https://github.com/electron/electron/releases/tag/v14.0.0 you mention in the PR description, did you also check we're not impacted by https://www.electronjs.org/docs/breaking-changes#planned-breaking-api-changes-140 ?
2. Should we do a direct jump to 15? 15.1.0 is out, and [15.0.0](https://github.com/electron/electron/releases/tag/v15.0.0) seems light on breaking changes.

**Comment by TheCleric** [comment]
> @TheCleric two questions:
> 
> 1. In addition to checking https://github.com/electron/electron/releases/tag/v14.0.0 you mention in the PR description, did you also check we're not impacted by https://www.electronjs.org/docs/breaking-changes#planned-breaking-api-changes-140 ?

I did now, and we're good.

> 2. Should we do a direct jump to 15? 15.1.0 is out, and [15.0.0](https://github.com/electron/electron/releases/tag/v15.0.0) seems light on breaking changes.

Actually this is something I wanted to bring up with you. Electron is now on an 8 week release cycle, so do we want to follow them completely and get on latest as soon as possible or do we want to move to the prior release upon initial latest release (i.e., go to v14 upon release of v15, etc.)?

What are your thoughts?

**Comment by ronjouch** [comment]
> I did [check both places] now, and we're good.

@TheCleric 👍

> this is something I wanted to bring up with you. Electron is now on an 8 week release cycle, so do we want to follow them completely and get on latest as soon as possible or do we want to move to the prior release upon initial latest release (i.e., go to v14 upon release of v15, etc.)? What are your thoughts?

@TheCleric I don't have very formed feelings about this. Whatever makes sense for us and our users; the usual bleeding-edge-ness vs. stability tradeoff. Do you have any preference?

**Comment by TheCleric** [comment]
> @TheCleric I don't have very formed feelings about this. Whatever makes sense for us and our users; the usual bleeding-edge-ness vs. stability tradeoff. Do you have any preference?

@ronjouch I'm about in the same boat. My thought is either:
1) Bleeding edge plus a stability period (2 weeks?)
or
2) My suggestion above about just staying on bleeding edge - 1.

I think 1 will keep us more up to date, but 2 could keep us more likely to avoid breaking changes, though it's less "avoid" and more "kick the can down the road".

Honestly my bigger concern is I don't think either of us have the time right now to fully fix most of the bugs coming through, and there has not been a lot of community contribution, so I feel like we're caught between a rock and a hard place. Upgrading will likely lead to new edge case bugs where thinks work SLIGHTLY differently (I think we're seeing quite a bit of this with new window/tab creation at the moment), so I'd assume this more frequent upgrade schedule will fix security risks, but will also possibly cause more bugs. Though I may be in a bit of a pessimistic/cynical mood. 😈 

What are your thoughts?

**Comment by TheCleric** [comment]
> @TheCleric and here's feedback from testing on Linux. Manual smoke tests all passed, I just saw a couple of errors.
> 
> ## Errors & deprecation warnings on opening the nativefier test app
> ```
> ***** SMOKE TEST 1: Test checklist *****
> [omitted for brevity]
> *** Running app
> [115959:1004/093842.418260:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in processgpu-process.
> (node:115924) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
> (Use `nativefier-smoke-test-1 --trace-warnings ...` to show where the warning was created)
> ```
> 
> ## Errors when opening the console
> ```
> [116957:1004/094540.289326:ERROR:CONSOLE(168)] "Electron sandbox_bundle.js script failed to run", source: electron/js2c/sandbox_bundle.js (168)
> [116957:1004/094540.289417:ERROR:CONSOLE(168)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: electron/js2c/sandbox_bundle.js (168)
> ```

This is VERY strange. I'm not seeing any of this on Mac. Possible related to https://github.com/electron/electron/issues/31185 ?

**Comment by ronjouch** [comment]
> my bigger concern is I don't think either of us have the time right now to fully fix most of the bugs coming through, and there has not been a lot of community contribution, so I feel like we're caught between a rock and a hard place. Upgrading will likely lead to new edge case bugs where thinks work SLIGHTLY differently (I think we're seeing quite a bit of this with new window/tab creation at the moment), so I'd assume this more frequent upgrade schedule will fix security risks, but will also possibly cause more bugs.

@TheCleric yup. Regarding community contributions, we could be more vocal that we need more hands. In the past I experimented with a message at the top of README.md / the repo page, but recently I was thinking we could be a bit more visible and emit a short non-verbose log message. Something at the beginning of running Nativefier along the lines of `Hi! Nativefier is minimally maintained these days, and needs more hands. If you have the time & motivation, halp on bugfixes & maintenance very welcome.`

**Comment by ronjouch** [comment]
> Couldn't hurt. Want me to add it to my 13.5.1 PR, or submit a separate PR?

Sure, go ahead! Thanks 🙂

**Comment by mattruzzi** [comment]
@ronjouch @TheCleric  I have an M1 mac with macOS, Linux, and Windows parallels vms so I can test if you have any specific thing that needs to be tested. 
What else needs to be done before this can be merged?
Also, should we just jump to [electron 16](https://github.com/electron/electron/releases/tag/v16.0.0) which only has two breaking changes?

> 
    - The crashReporter API is now powered by Crashpad on Linux. #30278
    - Usage of the desktopCapturer.getSources API from the renderer process has been deprecated and will be removed. 30721

**Comment by ronjouch** [comment]
> @ronjouch @TheCleric I have an M1 mac with macOS, Linux, and Windows parallels vms so I can test if you have any specific thing that needs to be tested. What else needs to be done before this can be merged? Also, should we just jump to [electron 16](https://github.com/electron/electron/releases/tag/v16.0.0) which only has two breaking changes?

@mattruzzi yup, was asking the same questions at https://github.com/nativefier/nativefier/pull/1288#issuecomment-932850757 . I agree we can jump to 15 or even 16, I have the feeling the warnings mentioned above are not so big of a problem, and if they are, as per our current "minimal maintenance" mode, well we'll let users push PRs for them.

Today or tomorrow I will update this PR to Electron 16, do a Linux smoke test, ping you for an extra macOS+Windows smoke test, and if not utterly broken let's cut a release and call it a day.

**Comment by ronjouch** [comment]
@TheCleric @mattruzzi meeeeeeeeeeeeeeerry December 25! The PR is updated to Electron 16 and `npm run test:manual` smoke tests pass for me under Linux. Can you give this a macOS (@TheCleric) and Windows (@mattruzzi) try? Thaaaaaaaaanks, and thanks @mattruzzi for the reminder. Breaking changes notes:

- Electron 15: no breaking changes for us
- Electron 16:
    - One very minor [breaking change in crashReporter](https://www.electronjs.org/docs/latest/breaking-changes#behavior-changed-crashreporter-implementation-switched-to-crashpad-on-linux), fixed by no longer calling `crashReporter.start`, as instructed by the breaking changes notes.
    - Not a breaking change, but a change in Electron typings: I had to adjust the tests, as an export we used is no longer available. But it's better that way anyway, as using and spying on the local `window` is what we want (see the code for what I mean)

As mentioned earlier, given our "minimal maintenance" mode, I'd like to not rathole on this. If basic smoke tests run fine on Windows and Mac, let's ship this and be done with it. Do report warnings if you see new ones, but if they are tolerable warnings and we end up anywhere above "not horribly broken for basic usage", let's ship this and let users submit PRs for broken non-basic scenarios they care about.

**Comment by mattruzzi** [comment]
Are the devtools supposed to be blue? 
Screenshot 2021-12-25 110118
Screenshot 2021-12-25 110432

**Comment by mattruzzi** [comment]
Also, I got an error on windows when running the second and third smoke tests. 
```
***** SMOKE TEST 3: Setting up test and building app... *****


    Hi! Nativefier is minimally maintained these days, and needs more hands.
    If you have the time & motivation, help with bugfixes and maintenance is VERY welcome.
    Please go to https://github.com/nativefier/nativefier and help how you can. Thanks.



Processing options...
Cannot automatically retrieve the app icon: Error: Request failed with status code 401
    at createError (C:\Users\matthew\Documents\nativefier\nativefier\node_modules\page-icon\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\matthew\Documents\nativefier\nativefier\node_modules\page-icon\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\matthew\Documents\nativefier\nativefier\node_modules\page-icon\node_modules\axios\lib\adapters\http.js:269:11)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  config: {
    url: 'https://authenticationtest.com/HTTPAuth/',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.4'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'authenticationtest.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'authenticationtest.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 60,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET /HTTPAuth/ HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/0.21.4\r\n' +
      'Host: authenticationtest.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/HTTPAuth/',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 0,
      httpVersion: '1.0',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 401,
      statusMessage: 'Unauthorized',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://authenticationtest.com/HTTPAuth/',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 36,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'authenticationtest.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://authenticationtest.com/HTTPAuth/',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 401,
    statusText: 'Unauthorized',
    headers: {
      date: 'Sat, 25 Dec 2021 19:09:05 GMT',
      server: 'Apache/2.4.41 (Ubuntu)',
      'strict-transport-security': 'max-age=63072000; includeSubDomains; preload',
      'cache-control': 'no-cache,no-store, no-store, no-cache, must-revalidate',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '1; mode=block',
      'referrer-policy': 'same-origin',
      'x-content-type-options': 'nosniff',
      'feature-policy': "autoplay 'none'; camera 'none'; document-domain 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; microphone 'none'; midi 'none'; payment 'none'; vr 'none'",
      pragma: 'no-cache, no-cache',
      'set-cookie': [Array],
      expires: 'Thu, 19 Nov 1981 08:52:00 GMT',
      'www-authenticate': 'Basic realm="u=User,p=Pass"',
      'content-length': '2893',
      connection: 'close',
      'content-type': 'text/html; charset=UTF-8'
    },
    config: {
      url: 'https://authenticationtest.com/HTTPAuth/',
      method: 'get',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      transitional: [Object],
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /HTTPAuth/ HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Host: authenticationtest.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/HTTPAuth/',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'authenticationtest.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: '<!DOCTYPE html>\n' +
      '<html lang="en">\n' +
      '\t<head>\n' +
      '\t\t<meta charset="utf-8">\n' +
      '\t\t<meta name="viewport" content="width=device-width, initial-scale=1">\n' +
      '\t\t<meta name="description" content="This site contains some examples of the ways web applications accept authentication. You can use these to test your scripts ability to authentication to them.">\n' +
      '\t\t<title>Authentication Test</title>\n' +
      '\t\t<link href="https://authenticationtest.com/assets/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">\n' +
      '\t\t<link rel="icon" href="https://authenticationtest.com/assets/favicon.png">\n' +
      '\t</head>\n' +
      '\t<body>\n' +
      '\t\t<nav class="navbar navbar-expand-lg navbar-dark bg-primary">\n' +
      '\t\t\t<a class="navbar-brand" href="https://authenticationtest.com/">\n' +
      '\t\t\t\t<img src="https://authenticationtest.com/assets/favicon.png" width="30" height="30" class="d-inline-block align-top" alt="Authentication Test Icon">Authentication Test</a>\n' +
      '\t\t\t<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">\n' +
      '\t\t\t\t<span class="navbar-toggler-icon"></span>\n' +
      '\t\t\t</button>\n' +
      '\t\t\t<div class="collapse navbar-collapse" id="navbarSupportedContent">\n' +
      '\t\t\t\t<ul class="navbar-nav mr-auto">\n' +
      '\t\t\t\t\t<li class="nav-item">\n' +
      '\t\t\t\t\t\t<a class="nav-link" href="https://authenticationtest.com/">Auth Menu</a>\n' +
      '\t\t\t\t\t</li>\n' +
      '\t\t\t\t\t<li class="nav-item">\n' +
      '\t\t\t\t\t\t<a class="nav-link" href="https://authenticationtest.com/statusCode/?code=200">Status Codes</a>\n' +
      '\t\t\t\t\t</li>\n' +
      '\t\t\t\t\t<li class="nav-item">\n' +
      '\t\t\t\t\t\t<a class="nav-link" href="https://authenticationtest.com/coverage/?id=1">Page 1</a>\n' +
      '\t\t\t\t\t</li>\n' +
      '\t\t\t\t\t<li class="nav-item">\n' +
      '\t\t\t\t\t\t<a class="nav-link" href="https://authenticationtest.com/about/">About</a>\n' +
      '\t\t\t\t\t</li>\n' +
      '\t\t\t\t\t<li class="nav-item">\n' +
      '\t\t\t\t\t\t<a class="nav-link" href="https://authenticationtest.com/totp/">TOTPGen</a>\n' +
      '\t\t\t\t\t</li>\n' +
      '\t\t\t\t\t<li class="nav-item">\n' +
      '\t\t\t\t\t\t<a class="nav-link" href="https://authenticationtest.com/xssDemo/">XSS Demo</a>\n' +
      '\t\t\t\t\t</li>\n' +
      '\n' +
      '\t\t\t\t\t\n' +
      '\t\t\t\t</ul>\n' +
      '\t\t\t</div>\n' +
      '\t\t\t<span class="navbar-text">\n' +
      '\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tPlease Sign In\n' +
      '\t\t\t\t\t\t\t\t\t\t\t\t</span>\n' +
      '\t\t</nav>\n' +
      '\t\t<div class="container">\n' +
      '\t\t\t\n' +
      '<h1>Login Failure</h1>\n' +
      '<div class="alert alert-danger">Sorry -- You have not successfully logged in. If you were trying HTTP Auth, clear your browser cache.</div>\n' +
      '\n' +
      '\t\t</div>\n' +
      '\t\t<footer class="text-center">\n' +
      '\t\t\t<hr>\n' +
      '\t\t\tCopyright &copy;2019-2021 <strong>Robert Lerner</strong>, All Rights Reserved. | <a href="https://authenticationtest.com/privacy/">Privacy Policy</a>\n' +
      '\t\t</footer>\n' +
      '\t\t<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>\n' +
      '\t\t<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>\n' +
      '\t</body>\n' +
      '</html>'
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

Preparing Electron app...

Converting icons...

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
Packaging app for platform win32 x64 using electron v16.0.5

Finalizing build...
App built to C:\Users\matthew\AppData\Local\Temp\nativefier-manual-test-auth-prompt-vHxGJ\nativefier-smoke-test-3-win32-x64, move to wherever it makes sense for you and run the contained .exe file.

```

**Comment by ronjouch** [comment]
@mattruzzi thanks for the fast tests.

> Are the devtools supposed to be blue?

They didn't use to, but indeed, now with Electron >13 it looks like our inject code applies to DevTools too. Clearly unproblematic to release, if someone is annoyed by it they can dig into it and fix it.

> Also, I got an error on windows when running the second and third smoke tests.

Indeed, reproduced. When failing to infer a website icon, we log and proceed, but we used to do a bad job at logging, logging the whole ginormous error rather than just the message. This logging nit aside, the log-and-proceed behavior is alright, that's what we want. I pushed a little logging fix.

**Comment by mattruzzi** [comment]
@ronjouch We should also solve #848 so when we release the new version it will be available on docker.

**Comment by TheCleric** [comment]
All automated and manual tests pass on MacOS 11.6.2!

**Comment by ronjouch** [comment]
Great. Thanks for the tests, frendz. Will cut a release tomorrow or soon-ish.

**Comment by loxK** [comment]
@TheCleric This broke widevine builds the version prefix changed from `-wvvmp` to `+wvcus ` . [See code](https://github.com/nativefier/nativefier/blob/b9c5e2b464fffe9d842f6dd0f0fec52b8f4405ed/src/options/optionsMain.ts#L163)

As [see here](https://github.com/castlabs/electron-releases/releases/tag/v16.0.5%2Bwvcus):

> The v16 series of Electron for Content Security, labeled wvcus, moves to using the Component Updater Service to handle installation of the Widevine CDM, and has incompatible API updates compared to the previous wvvmp releases.

**Comment by ronjouch** [comment]
> This broke widevine builds

Thanks for the notice, @loxK. Fixed in 5e3c23267a57f0f61e97e9367c780e0db2c728d9, will cut a release soon.

**Pull request merged**
