### PR TITLE
Switch issues from GitHub "issue templates" to new/beta "issue forms" (fix #1258)

### LINKED ISSUE #1258: [Project internals] Switch issues from GitHub "issue templates" to new/beta "issue forms"
We use GitHub "issue templates" to push / force users to write good issues containing all the necessary information. See [our `.github/ISSUE_TEMPLATE` folder](https://github.com/nativefier/nativefier/tree/master/.github/ISSUE_TEMPLATE).

GitHub recently released a new feature called "issue forms", which are basically ***structured*** issue templates, enabling a clearer separation between issue template filler and the actual issue, for better (?) user experience. See:

- [GitHub Docs / Issue & PR templates / Creating issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)
- [GitHub Docs / Issue & PR templates / Syntax for GitHub's form schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)

It looks neat and I think I'll give it a try these days. This is a little issue

1. To remind me to try it
2. To encourage passersbys who already used it to give feedback about it: how did it go for you? (As a user or project maintainer?) Does it work as advertised? Any annoying limitations? Does it look like a great idea but turns out to be inflexible from a user perspective in the end? Etc; all feedback welcome 🙂.

### PR DESCRIPTION
**Pull request by mattruzzi**
Closes #1258

### CODE REVIEW

**Comment by ronjouch** [comment]
:wave: @mattruzzi. Is this ready for review, or work-in-progress? If ready, please mark as `Ready for review`.

**Comment by mattruzzi** [comment]
@ronjouch Should bug reports have `[Bug]: ` at the beginning of the title? It was used in the GitHub issue forms example but  is the bug label enough?

**Comment by ronjouch** [comment]
> @ronjouch Should bug reports have `[Bug]: ` at the beginning of the title? It was used in the GitHub issue forms example but is the bug label enough?

@mattruzzi agreed, the bug label is enough.

And 👍 for marking as ready. I'll merge this soon and will follow-up by playing with it and probably tweaking a few knobs here and there. Thaaaaaaaanks for your work 🙂.

**Comment by mattruzzi** [comment]
@ronjouch If you want to play with it I have a test repo here: https://github.com/mattruzzi/issueformstest

**Comment by ronjouch** [comment]
Okayyyyyy let's try this! Merging, followup by probably a few commits to tinker further.

Thanks @mattruzzi !!!

**Pull request merged**
