### PR TITLE
Get rid of "docs" folder

### PR DESCRIPTION
**Pull request by ronjouch**
It contains a weird mix of stuff and hides valuable files from view at the root of the repo. Better to have:
- Docs like api.md & development.md visible at the root of the repo. Also, make them uppercase for convention/visibility, and rename `development.md` into `HACKING.md`, which is the conventional name for this kind of doc.
- Rest of the github/release-related hodgepodge (screenshots, scripts) in hidden folder `.github`

### CODE REVIEW

**Comment by TheCleric** [comment]
I'm mostly fine with this with one caveat:

I don't like the hiding things in the `.github` folder. It feels like lying to me as they are not Github Actions/Workflows/etc.. I think a better solution would be:

- Create a different hidden directory (.assets? .docs? .????)

Or

- Find a better home for these. Such as:
    - `generate-changelog`: Rename `icon-scripts` to `scripts` and move it there
    - `manual-test`: Same as `generate-changelog` or in `test-resources` (which I think `manual-test` is the only thing that cares about these resources anyway, so many rename it to `test`, place the script in there, and then move all the existing file into a `resources` in `test`)
    - The .gif and .png files are the tough ones. After doing some research the most popular solutions I've found are either:
        - Do what we're already doing and include them in your repo
        - Have a hosted website which you can link them from
        - Use this trick: 
            - This seems like the best choice to me and I tested out and was able to upload them without actually submitting the issue. Here they are:
            - `walkthrough`
            - `dock`
    - A note on these two images aside from this PR. They look a little dated in terms of both what you actually see in Nativefier and in terms of MacOS look and feel. (Also I like that progress bar, let's bring that back! lol)

I think that about covers my concerns otherwise.

**Comment by ronjouch** [comment]
@TheCleric 

> I don't like the hiding things in the `.github` folder. It feels like lying to me as they are not Github Actions/Workflows/etc..

I don't either, but remember we're here talking about just *2* internal files (we could say 4, but I'll argue it's only 2, see below). I feel the alternatives you propose are too weighty for a need that is to just hide two internal files and two images for our GitHub page.

1. You're right that the strict purpose of `.github` is to store workflows/issues files, not random stuff. Still, I'm not feeling very dirty to shove `dock-screenshot.png` and `walkthrough.gif` in here. These images are here to be displayed in GitHub! So, to my eyes, these feel at home in `.github`.
2. Then, okay `generate-changelog` and `manual-test` are two internal files, called from `npm` anyway. I want to hide them from view, and creating a new folder for just these two will cause a folder consuming space in our root, taking mental space but ignored by everybody. And that's why I want to shove them in `.github` too: they're of no concern to the passerby cloning the repo to work on a PR, they don't deserve a folder.

So, I maintain I'd like to shove these 2\*2 things in `.github`. It's a minor dirtiness, to keep our root neat & tidy.

Regarding your other suggestions,

> `test-resources`

Hey, this one is unused now! I generate my js/css to inject from the `manual-test` script, and the icons are unused. Nuking the folder; wheeeee one less thing in `/` 🙂🙂🙂.

> `generate-changelog`: Rename `icon-scripts` to `scripts` and move it there

No: I don't want to mix runtime-user-run icon-generation scripts with build/release/test scripts

> The .gif and .png files are the tough ones. After doing some research the most popular solutions I've found are either:
> 
> 1. Do what we're already doing and include them in your repo
> 2. Have a hosted website which you can link them from
> 3. Use this trick https://ardalis.com/add-images-easily-to-github/:

Solutions 2. and 3. are too complicated/unfriendly vs. the easy solution 1. we have now. I much prefer shoving stuff in `.github` and keeping solution 1.

> A note on these two images aside from this PR. They look a little dated in terms of both what you actually see in Nativefier and in terms of MacOS look and feel.

True! Many of our users runs Macs, where Nativefier's appeal is to have "an app running in your dock", so I'd like a refresh that's still from a Mac. I think you run a Mac, right? Can you update them in a separate PR? If/when doing it, pls use a background wallpaper that is less noisy / difficult-to-compress than the current one, to produce a smaller GIF + PNG. Then run the GIF through Gifski, and the PNG through PNGquant, for minimal file size.

Note: yeah we still want a GIF for the animation. Even if GitHub recently added support for mp4, our README is rendered elsewhere e.g. at npm, so we definitely want to keep a GIF.

> (Also I like that progress bar, let's bring that back! lol)

😄 oh booooy. Nuking this janky progress bar was good gooooooood riddance 😄.

**Comment by TheCleric** [comment]
@ronjouch 

> > I don't like the hiding things in the `.github` folder. It feels like lying to me as they are not Github Actions/Workflows/etc..
> 
> I don't either, but remember we're here talking about just _2_ internal files (we could say 4, but I'll argue it's only 2, see below). I feel the alternatives you propose are too weighty for a need that is to just hide two internal files and two images for our GitHub page.
> 
> So, I maintain I'd like to shove these 2*2 things in `.github`. It's a minor dirtiness, to keep our root neat & tidy.

I don't think I agree, but it's also not important enough to continue to discuss. 😆 

> Regarding your other suggestions,
> 
> > `test-resources`
> 
> Hey, this one is unused now! I generate my js/css to inject from the `manual-test` script, and the icons are unused. Nuking the folder; wheeeee one less thing in `/` 🙂🙂🙂.

😄 

> > `generate-changelog`: Rename `icon-scripts` to `scripts` and move it there
> 
> No: I don't want to mix runtime-user-run icon-generation scripts with build/release/test scripts

That's understandable.

> > The .gif and .png files are the tough ones. After doing some research the most popular solutions I've found are either:
> > 
> > 1. Do what we're already doing and include them in your repo
> > 2. Have a hosted website which you can link them from
> > 3. Use this trick https://ardalis.com/add-images-easily-to-github/:
> 
> Solutions 2. and 3. are too complicated/unfriendly vs. the easy solution 1. we have now. I much prefer shoving stuff in `.github` and keeping solution 1.

👍 

> I think you run a Mac, right?

Yep. 😄 

> Can you update them in a separate PR? If/when doing it, pls use a background wallpaper that is less noisy / difficult-to-compress than the current one, to produce a smaller GIF + PNG. Then run the GIF through Gifski, and the PNG through PNGquant, for minimal file size.

Do you know of a good screen recorder to do this?

> Note: yeah we still want a GIF for the animation. Even if GitHub recently added support for mp4, our README is rendered elsewhere e.g. at npm, so we definitely want to keep a GIF.

Yeah I wouldn't have even thought to use MP4.

> 😄 oh booooy. Nuking this janky progress bar was good gooooooood riddance 😄.

Really? What was the matter with it?

**Comment by TheCleric** [comment]
@ronjouch I'm good with this if you are.

**Review by TheCleric — APPROVED** [review]

**Comment by ronjouch** [comment]
> I don't think I agree, but it's also not important enough to continue to discuss. :laughing: 

👍, merging.

> > oh booooy. Nuking this janky progress bar was good gooooooood riddance :smile:
> 
> Really? What was the matter with it?

@TheCleric it was jankier than janky. It was by no means reliable, causing user frustration, and wasn't super pretty in the code either. I replaced it in 8.0.0 (the move to TS) with what we have now: more logging, indicating progress and helping debuggability (by asking users for `--verbose` logs).

**Comment by ronjouch** [comment]
> Do you know of a good screen recorder to do this?

@TheCleric I know on Linux, but I'm clueless on Mac, sorry.

**Comment by mattruzzi** [comment]
For a screen recorder you can use the built in Mac [QuickTime](https://support.apple.com/en-us/HT208721#quicktime) app, or for something more advanced you can use [Streamlabs OBS](https://streamlabs.com/) ([standard OBS](https://obsproject.com/) records in a format not compatible with Gifski, but the Streamlabs version works).

**Comment by TheCleric** [comment]
> For a screen recorder you can use the built in Mac [QuickTime](https://support.apple.com/en-us/HT208721#quicktime) app, or for something more advanced you can use [Streamlabs OBS](https://streamlabs.com/) ([standard OBS](https://obsproject.com/) records in a format not compatible with Gifski, but the Streamlabs version works). 

Thanks @mattruzzi !

**Pull request merged**
