### PR TITLE
App: Automatically consider known login pages as internal (fix #706)

### LINKED ISSUE #706: External login pages open in external browser, breaking login or asking users to know about --internal-urls. Nativefier should automatically open those internally.
### Description

Hello i'm trying to use nativefier to login into my youtube music,
But when i click login it opens browser, i login. and nothing happens.

### Steps to reproduce issue

Install it with music.youtube.com

### Details

- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: nativefier music.youtube.com
- Version of Nativefier (run `nativefier --version`): Current
- Version of node.js (run `node --version`): current
- OS: win 10 64b
- Error message / stack trace (if any):

afbeelding

### PR DESCRIPTION
**Pull request by TheCleric**
This is a proposal to solve #706. We can wait for more feedback on that issue before merging.

### CODE REVIEW

**Comment by TheCleric** [comment]
Also @ronjouch I thought of fixing something related here as part of this. Our documentation says `--internal-url` works off the second level domain (e.g., example.com and subdomain.example.com have the same second level domain), but that is not reflected in our code. Could I also remedy that?

**Comment by ronjouch** [comment]
Thanks! On first glance, this looks excellent, I don't have any comment, and great job on the cleanup & tests :clap: . So, yup, let's *"wait for more feedback on that issue"*, like maybe a week, then I'll merge.

---

> Also @ronjouch I thought of fixing something related here as part of this. Our documentation says `--internal-url` works off the second level domain (e.g., example.com and subdomain.example.com have the same second level domain), but that is not reflected in our code. Could I also remedy that?

@TheCleric this is something that I changed days ago in 6b266b78150 🙂 :

> **(Attempt to) get rid of deprecated app dep `wurl`**
>
> This one may be problematic, as it used to do TLD stuff:
> https://github.com/websanova/node-url/blob/7982a613bc/wurl.js#L4
> 
> So, the new WHATWG-URL-based implementation will consider
> `asana.com` to be "external" to `app.asana.com`, contrarily to before.
> Given the nature of Nativefier, I think it's actually what to expect,
> that in this case your "out of the app", and in e.g. asana landing's page,
> which you'd expect to see in your browser.
>
> Let's see if users disagree with that.

, then I forgot to mention it in the release notes of 42.3.0 :facepalm: .

As I was examining what to do with this deprecated dep, I wondered if I could altogether get rid of the dep (as you've seen elsewhere :grin:), and here I didn't want to do the job on my own, as that'd mean having to bundle and monitor the list of TLDs and Second-Level-Domains. So, I'm trying this simpler way that might anyway be good for Nativefier's use case (where users typically nativefy `app.foo.com` that is typically different from `foo.com`, which in my experience I'd expect to open externally). Maybe I'm wrong and missing use cases that will cause user complaints; if so, I'll adjust.

Any opinion?

**Comment by TheCleric** [comment]
> As I was examining what to do with this deprecated dep, I wondered if I could altogether get rid of the dep (as you've seen elsewhere 😁), and here I didn't want to do the job on my own, as that'd mean having to bundle and monitor the list of TLDs and Second-Level-Domains. So, I'm trying this simpler way that might anyway be good for Nativefier's use case (where A. cookie logic is actually per domain, and B. users typically nativefy `app.foo.com` that is typically different from `foo.com`, which in my experience I'd expect to open externally). Maybe I'm wrong and missing use cases that will cause user complaints; if so, I'll adjust.
> 
> Any opinion?

I know it was problematic earlier when trying to do an app for `https://evernote.com` as its login page is on `www.evernote.com`. Maybe there is a compromise where no subdomain as an app root = all subdomains, or no subdomain and www are equivalent in all cases.

**Comment by ronjouch** [comment]
> I know it was problematic earlier when trying to do an app for `https://evernote.com` as its login page is on `www.evernote.com`. Maybe there is a compromise where no subdomain as an app root = all subdomains, or no subdomain and www are equivalent in all cases.

@TheCleric good catch, thanks 🙂. Pls review https://github.com/nativefier/nativefier/pull/1126 .

**Comment by ronjouch** [comment]
@TheCleric heads up, trivial need-to-keep-both conflict since I merged #1126. Letting you merge/rebase the way you like it.

**Comment by ronjouch** [comment]
@TheCleric I was about to merge this, then reconsidered one little thing (yes I wrote "little", I'm not reconsidering this whole thing 😅).

I'm re-considering having the extra flag. I'm not so sure this will harm a lot of use cases. I'd like to 1. merge this PR, 2. immediately follow up with a small commit removing the flag, 3. release (I'm not asking you any extra work, and am leaving a trace of considering the flag). If people complain with a valid reason, we'll restore the flag with a quick revert, else we're happy with one less flag and a reasonably-handled breaking change.

Thoughts / objections?

**Comment by ronjouch** [comment]
Thanks @TheCleric . Following up with what I wrote above:

> 1. merge this PR, 2. immediately follow up with a small commit removing the flag & adjusting api.md, 3. release with the change well-documented / asking for feedback if this is problematic to anyone.

**Comment by ronjouch** [comment]
@TheCleric in https://github.com/nativefier/nativefier/pull/1124/commits/449684e4df85932f63f9320b194bbb60f0491fe5 I also added a bit of doc in api.md / --internal-urls

**Comment by ronjouch** [comment]
And here's the revert, ready to un-revert if anyone offers a convincing take that the option was needed: https://github.com/nativefier/nativefier/commit/74a7d3375df2421ec167fa62fd28d05b505e852d

**Pull request merged**
