### PR TITLE
Fix regressions in opening windows/tabs, update browser versions

### PR DESCRIPTION
**Pull request by TheCleric**
All manual tests pass.

### CODE REVIEW

**Review by ronjouch — APPROVED** [review]

**Comment by TheCleric** [comment]
@ronjouch do we want to cut a release first before we merge?

**Comment by TheCleric** [comment]
@ronjouch before we merge this, we may want to take a look at something. I was testing deeper and was encountering all kinds of issues with new windows and new tabs (either they wouldn't open or they would be blank). I thought it was something I did, but it looks like it happened between v44.0.7 and v45.0.0.

Can you confirm?

**Comment by TheCleric** [comment]
For me I think I've narrowed it down to Electron 13. If I run with `-e 12.1.1` everything works. We may need to abandon v13 for now until we can figure out why it broke our windows. :(

**Comment by ronjouch** [comment]
> For me I think I've narrowed it down to Electron 13. If I run with `-e 12.1.1` everything works. We may need to abandon v13 for now until we can figure out why it broke our windows. :(

@TheCleric note that your PR doesn't upgrade Electron to 13.4.0, it was already upgraded two days ago in e222e99b56f7f3b8a1f8c5b42dc497d1da77a765 (changing app devDeps `"electron": "^13.1.7"` to `"electron": "^13.4.0"` doesn't do much - typing mostly - as what matters is `DEFAULT_ELECTRON_VERSION`). Renaming your PR to `Update browser versions`, which is the bulk of what your PR does.

→ Is it Electron 13.4.0 that is problematic, or previous releases like 13.1.7 used in Nativefier 45.0.0 was okay? And okay, I'll make a couple tests myself too

**Comment by ronjouch** [comment]
> We may need to abandon v13 for now until we can figure out why it broke our windows. :(

@TheCleric one more thing: do your regressions also happen with Electron 14.0.1 (released a couple weeks ago) and 15.0.0 (released today) ?

**Comment by TheCleric** [comment]
> → Is it Electron 13.4.0 that is problematic (and previous releases like 13.1.7 used in Nativefier 45.0.0 was okay), or is it 13.x ? I'll make a couple tests myself too.

I think it's 13.x, v45.0.0 was showing me the same issues

> @TheCleric one more thing: do these regressions also happen with Electron 14.0.1 (released a couple weeks ago) and 15.0.0 (released yesterday) ?

Just checked, and yes they do. I'm beginning to wonder if it's due to the fact that we still rely on the deprecated `.on('new-window')` instead of the new `.setWindowOpenHandler`. I'll try some experiments to see what I can get working, but to be clear here are my current findings:

- The last known build of Nativefier that does not present these issues is v44.0.7 (the last build with v12 as default).
- Using our current version with the flag `-e 12.1.1` (latest 12 as of right now) seems to fix these issues.

**Comment by TheCleric** [comment]
@ronjouch I've got it figured out, and it wasn't what I thought. The behind the scenes of the `onHeadersReceived` callback must have changed. We use that to inject CSS and provide the headers given to us in the callback, but somehow in Electron 13+ that makes the new window opener decide not to load anything. So I've remedied that.

As well in trying to determine the issue, I found the source for a few other small bugs (like why we get reports of multiple tabs getting opened) and fixed those as well since this all revolved around window open events/logic.

One strange thing that I noticed that I can't track down: on my Mac, when you open a new tab, the window briefly disappears and then reappears with the new tab. I'll file a bug and try to track it down later.

As well since this didn't involve our lack of transition to `. setWindowOpenHandler`, I did not include a transition to that over `.on('new-window')` but will probably do so soon since we're on borrowed time with that deprecated API.

Also I know the tests are broke. 🤦   I'll get those fixed in a few.

**Comment by TheCleric** [comment]
@ronjouch FYI (and no rush) waiting for you to make sure you're okay with the other changes since your initial approval.

**Comment by ronjouch** [comment]
@TheCleric thanks :clap: . I played a bit on a build of your branch and didn't notice anything weird. Manual tests (including your addition to test opening in new window) and random testing went fine.

**Review by ronjouch — APPROVED** [review]

**Comment by ronjouch** [comment]
Released in https://github.com/nativefier/nativefier/releases/tag/v45.0.2

**Pull request merged**
